
version: '3.8'

services:
  uscis-photo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Cambia el mapeo de puerto si es necesario
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Opcional: mapear volúmenes si necesitas persistencia
      - ./logs:/app/logs
