
version: '3.8'

services:
  uscis-photo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7170:7170"  # Mapear puerto 7170 del host al 7170 del contenedor
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Aumentar límite de memoria para Node.js
      - NODE_OPTIONS=--max-old-space-size=8192
      # Forzar el uso del método alternativo en Docker
      - USE_ALTERNATIVE_BACKGROUND_REMOVAL=true
      # Marcar explícitamente como entorno Docker
      - DOCKER_CONTAINER=true
      - RUNNING_IN_DOCKER=true
    volumes:
      # Opcional: mapear volúmenes si necesitas persistencia
      - ./logs:/app/logs
      # Cache para modelos de transformers
      - transformers_cache:/app/.cache/transformers
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7170"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2'
        reservations:
          memory: 4G
          cpus: '1'

volumes:
  transformers_cache:
    driver: local
